# Generated by Django 2.2.19 on 2022-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateTimeField(verbose_name='End mailing date'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(verbose_name='Start mailing date'),
        ),
    ]
